#!/bin/sh

set -e

DISK=$AUTOPKGTEST_TMP/disk

cleanup () {
  umount /mnt || true
  [ "$LOOP" ] && losetup -d $LOOP
  rm -f $DISK $DISK.image || true
}

trap "cleanup" 0 2 3 15

printf "\n=== losetup ===\n"
dd if=/dev/zero of=$DISK bs=1M count=200 2>&1
LOOP=$(losetup --find --show $DISK)

printf "\n=== mkfs ===\n"
mkfs.ocfs2 --force --mount local --block-size $(stat -f $DISK --format='%s') $DISK 2>&1

printf "\n=== mount ===\n"
mount -o nocluster $LOOP /mnt
df /mnt
